### ISSUE TITLE
error loading location: unknown time zone Asia/Shanghai

### ISSUE THREAD

**Issue by sa-y0nara** [only9464/Fuck-YuKeTang#1]
windows  11 64位条件下运行会出现这个情况，从而阻止程序运行。

**Comment by only9464** [comment]
非常感谢提出问题！
本程序用的是统一时间UTC+8，所以用的是上海时间。
请问有没有相关截图以便后续适配！😉🥰🥰

**Comment by sa-y0nara** [comment]
好的！我觉得可能是windows自带时区缺失的问题。win11 日期和时间 中没有该时区，代表中国的是 UTC+08:00 北京，重庆，香港特别行政区，乌鲁木齐  
这个程序在ubuntu上运行得很好。  
你是在cygwin环境中运行的吗？ 
![111](https://github.com/user-attachments/assets/754c8f57-79fc-48a8-820b-7e92474d5aa8)

**Comment by sa-y0nara** [comment]
大概是这么回事。有人说，Windows的上海时区表示为Asia/ShangHai，Linux中表示为Asia/Shanghai，存在大小写的区别。

**Comment by only9464** [comment]
# 非常感谢持续反馈问题~
## 1.这个问题我大概了解了一下，确实有可能是win11系统缺失时区，我可以运行的win11系统时间相关配置如下：
![image](https://github.com/user-attachments/assets/8a4e43a9-c680-4017-a784-eac3b472c3f0)
## 2.程序并不是在cygwin环境中运行，项目用的是Golang语言，所有发布版本都是在windows11系统下进行交叉编译生成的
## 3.Go语言版本为：go version go1.22.2 windows/amd64
## 4.解决方法
**后续将在代码层面内置嵌入时区数据或使用固定时区偏移量来解决该问题，计划将在后续v0.0.3版本发布**
**如着急在出问题的环境下使用，建议尝试重置时间设置（我也不太确定能不能行）**

**Comment by only9464** [comment]
**你好，v0.0.3版本已发布，可以前往[Releases v0.0.3](https://github.com/only9464/Fuck-YuKeTang/releases/tag/v0.0.3)下载**
