### ISSUE TITLE
我在泰国有条路，虽然危险是危险了一点，但是利润很高

### ISSUE THREAD

**Issue by sa-y0nara** [only9464/Fuck-YuKeTang#2]
撞到了一个可以查题目答案的办法，只要有problemid+微操就行。要不要试试？

**Comment by sa-y0nara** [comment]
要的话我扔你邮箱里

**Comment by only9464** [comment]
哈哈，来!

**Comment by sa-y0nara** [comment]
扔过去啦！

**Comment by only9464** [comment]
好的，收到了 ，研究研究，嘻嘻嘻

**Comment by sa-y0nara** [comment]
哈哈哈，okok，我在邮箱那里又扔了点话，今天不打算搞这东西了，抓了一个下午的包，头昏了，你加油

**Comment by Violiate** [comment]
不会是教师端那个吧😂，昨晚我也扒了一下，headers里有一个authentication，但我扒到是RSA256 加密的，加密函数看晕了，是用你自己的uid和一些信息生成的key，理论上把secret key搞出来就可以搞到答案🧐

**Comment by sa-y0nara** [comment]
被你发现啦。解密不了就不要解密了，因为雨课堂内部的教师权限也是一坨💩，你随便生成一个拿来用都可以查到任意题目的答案。我在这个仓库提了个pull request，可以去看看，以极小的代价换来长期的自动作答，我认为是值当的。

**Comment by sa-y0nara** [comment]
看了包是觉得很荒唐的东西。但他就是能跑。只能说雨课堂那班东西唐完了

**Comment by only9464** [comment]
> 不会是教师端那个吧😂，昨晚我也扒了一下，headers里有一个authentication，但我扒到是RSA256 加密的，加密函数看晕了，是用你自己的uid和一些信息生成的key，理论上把secret key搞出来就可以搞到答案🧐

那是JWT令牌，加密格式在 10.87e7b6bd29b27734d3f5.js 文件里，
![image](https://github.com/user-attachments/assets/325c5007-1c3b-4d0a-92e8-ae4be40b351b)

**Comment by only9464** [comment]
> 被你发现啦。解密不了就不要解密了，因为雨课堂内部的教师权限也是一坨💩，你随便生成一个拿来用都可以查到任意题目的答案。我在这个仓库提了个pull request，可以去看看，以极小的代价换来长期的自动作答，我认为是值当的。

收到，我晚些时间测试一下

**Comment by Violiate** [comment]
那我觉得甚至可以调出来教师端的签到展示二维码，签到可以走那个二维码。从小程序入口和扫码的显示渠道还是不一样，会被发现

**Comment by only9464** [comment]
哈哈，那些被我抓到过的，不过没什么用，拿学生端的令牌去请求是获取不到的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "only9464/Fuck-YuKeTang"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月12日(星期六) 晚上7:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [only9464/Fuck-YuKeTang] 我在泰国有条路，虽然危险是危险了一点，但是利润很高 (Issue #2)





 
那我觉得甚至可以调出来教师端的签到展示二维码，签到可以走那个二维码。从小程序入口和扫码的显示渠道还是不一样，会被发现

**Comment by sa-y0nara** [comment]
二维码是搞不到了，但是二维码登录还是可以搞得到的。众所周知，在checkin课程的时候，会发一个json文件，在ykt.go里面形式大概是这样的：
![1](https://github.com/user-attachments/assets/68c9b86b-efb4-47d7-951c-f72722a3076c)
里面有一个叫source的东西，它的取值关乎着在后端记录的登入课堂方式。按照下面的方式可以找到不同代号对应的访问方式：在每一节课结课后在学生端点进去学习报告，大概就是下图的东西，然后对其抓包：
![2](https://github.com/user-attachments/assets/938c7ef6-71e6-4418-bca2-aadad91257d4)
在响应体中可以查看到一些代号对应的方式，常见的为以下几种：
![image](https://github.com/user-attachments/assets/b8cd1a0d-9700-4561-bfe3-8084e5cad0c6)
![image](https://github.com/user-attachments/assets/5e15a8d8-2862-44e8-9127-67aa212ed588)
![image](https://github.com/user-attachments/assets/31b16f6d-cf82-442b-9666-1fa1e178f49c)
![image](https://github.com/user-attachments/assets/35b8f8a5-18c3-4b34-a280-2188041399e2)
![image](https://github.com/user-attachments/assets/7b110671-79ca-400b-badf-8258e22e2051)
其中source为-1时是缺勤情况。 
也就是说，在往checkin发包的时候，只要把source设置成1，后端就会认为你是二维码扫描登录。我已经试过了，你们试试。

**Comment by sa-y0nara** [comment]
我发的这个图里面的ykt.go我已经改过了，main分支里面的source值是5

**Comment by Violiate** [comment]
曲线救国，秒哇
